### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by americoleonardo** [chriskonnertz/string-calc#9]
Hi Cris,

Congratulations for the calc tool, it is very useful and I hope this project helps many people in the community.

I have a questions about division by zero. I have a mathematic expression who converts many taxes in value to execute the algorithm, but one of this divisions have a 0 value, and in my console returns warning, and don't an Exception:

``Warning: Division by zero in /var/www/controlzinco/vendor/chriskonnertz/string-calc/src/ChrisKonnertz/StringCalc/Symbols/Concrete/Operators/DivisionOperator.php on line 32
``

There's a way to return an Exception in this case, or I need check this condition previously?

Thanks!

**Comment by chriskonnertz** [comment]
Hello,

consider the operator classes being wrappers around PHP operators. Since PHP is not throwing an exception, StringCalc is not as well.

You might ask: Why not just adding exception handling? Well that would be like opening Pandora's box. I like thing to be consistent. Adding exception handling in this case would force me to add it everywhere, in all symbol (operators, functions, ...) classes. I do not want to do that so I cannot add it in this special case.

But you can do it on your own.  Untested code example:

```php
class MyDivisionOperator extends \ChrisKonnertz\StringCalc\Symbols\Concrete\Operators\DivisionOperator
{
    /**
     * @inheritdoc
     */
    public function operate($leftNumber, $rightNumber)
    {
        if ($rightNumber == 0) {	
            throw new \InvalidArgumentException('Error: Division by zero detected.');	
        }
        return $leftNumber / $rightNumber;
    }
}

$symbol = new MyDivisionOperator;
$replaceSymbol = \ChrisKonnertz\StringCalc\Symbols\Concrete\Operators\DivisionOperator::class;

$stringCalc->addSymbol($symbol, $replaceSymbol);
```

By the way throwing an exception here is not a new idea: https://github.com/chriskonnertz/string-calc/commit/3e120dd3a2dc39ec1cab32907fefa9c914b2ef43#diff-56b0e1a02b594d0ecc09aff293384db6
